---
services:
  tagt.parameters:
    class: Tagt\Parameters
  tagt.find_command:
    class: Tagt\Command\FindCommand
    arguments:
      name: 'find'
      parameters: '@tagt.parameters'
  tagt.view_command:
    class: Tagt\Command\ViewCommand
    arguments:
      name: 'view'
      parameters: '@tagt.parameters'
  tagt.application:
    class: Symfony\Component\Console\Application
    calls:
      - [add, ['@tagt.find_command']]
      - [add, ['@tagt.view_command']]
